server:
  port:8080

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
